os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "9.1.0"

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g yarn@1.3.2
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - yarn lint
  - yarn build:prod

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
